version: "3"

services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ${ROOT_DIR}/data/redis:/data/

  web:
    build: .
    ports:
      - 0.0.0.0:8080:8080
    depends_on: 
      - redis
    command: gunicorn app:app -b :8080 -k gevent --log-level info
    env_file: .env